name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  tests:
    permissions:
      checks: write
    uses: ebsnet/CSRGenerator/.github/workflows/build.yml@master

  publish:
    name: Publish build artifacts
    needs: [tests]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"
      - name: Build
        run: ./gradlew build
      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/distributions/CSRGenerator-*.tar
            build/distributions/CSRGenerator-*.zip

  changelog:
    name: Update Changelog
    permissions:
      contents: write
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
